spring:
  application:
    name: demotuwei
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: tuwei
    password: 123456
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  #   default-property-inclusion: non_null

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080

logging:
  level:
    com:
      demotuwei: debug

mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapping/*/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
