spring:
  application:
    name: demotuwei
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useMysqlMetadata=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: tuwei
    password: 123456
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  #   default-property-inclusion: non_null
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    clean-disabled: true
    enabled: true
  devtools:
    livereload:
      port: 35730

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080

logging:
  level:
    com:
      demotuwei: debug

mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapping/*/*.xml
